blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('newsapp.urls')),
]

newsapp/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

from . import views
urlpatterns=[
    #path('',views.home,name='home'),
    path('',views.all_news,name='all-news'),
    path('detail/<int:id>',views.detail,name='detail'),
    path('all-category',views.all_category,name='all-category'),
    path('category/<int:id>',views.category,name='category'),
    path('contact', views.contact, name='contact'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsapp/models.py
from django.db import models

class Category(models.Model):
    title=models.CharField(max_length=200)
    category_image=models.ImageField(upload_to='imgs/')

    class Meta:
        verbose_name_plural='Categories'

    def __str__(self):
        return self.title

# News Model
class News(models.Model):
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    title=models.CharField(max_length=300)
    image=models.ImageField(upload_to='imgs/')
    detail=models.TextField()
    add_time=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural='News'

    def __str__(self):
        return self.title

# Comments
class Comment(models.Model):
    news=models.ForeignKey(News,on_delete=models.CASCADE)
    name=models.CharField(max_length=100)
    email=models.CharField(max_length=200)
    comment=models.TextField()
    status=models.BooleanField(default=False)

    def __str__(self):
        return self.comment

newsapp/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from .models import News, Category,Comment
def home(request):
    first_news=News.objects.first()
    three_news=News.objects.all()[1:3]
    three_categories=Category.objects.all()[0:3]
    return render(request,'home.html',{
        'first_news':first_news,
        'three_news':three_news,
        'three_categories':three_categories
    })

# All News
def all_news(request):
    all_news=News.objects.all()
    return render(request,'all-news.html',{
        'all_news':all_news
    })

# Detail Page
def detail(request,id):
    news=News.objects.get(pk=id)
    if request.method=='POST':
        name=request.POST['name']
        email=request.POST['email']
        comment=request.POST['message']
        Comment.objects.create(
            news=news,
            name=name,
            email=email,
            comment=comment
        )
        messages.success(request,'Comment submitted but in moderation mode.')
    category=Category.objects.get(id=news.category.id)
    rel_news=News.objects.filter(category=category).exclude(id=id)
    comments=Comment.objects.filter(news=news,status=True).order_by('-id')
    return render(request,'detail.html',{
        'news':news,
        'related_news':rel_news,
        'comments':comments
    })

# Fetch all category
def all_category(request):
    cats=Category.objects.all()
    return render(request,'category.html',{
        'cats':cats
    })


# Fetch all category
def category(request,id):
    category=Category.objects.get(id=id)
    news=News.objects.filter(category=category)
    return render(request,'category-news.html',{
        'all_news':news,
        'category':category
    })

def contact(request):
    return render(request, 'contact.html')

newsapp/templates/all-news.html
{% extends 'base.html' %}
{% block content %}
<main class="container mt-3 mb-5">
	<h3 class="border-bottom pb-1 my-4">All News</h3>
    <!-- News Box -->
    {% for news in all_news %}
	<div class="card mb-4 shadow">
	  <div class="row no-gutters">
	    <div class="col-md-3">
            <img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
	    </div>
	    <div class="col-md-8">
	      <div class="card-body">
	        <h5 class="card-title">{{news.title}}</h5>
	        <p class="card-text">{{news.detail}}</p>
	        <p class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-primary">Read Full</a></p>
	      </div>
	    </div>
	  </div>
    </div>
    {% endfor %}
</main>
{% endblock %}

newsapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}Home Page{% endblock %}</title>
	<!-- Bootstrap 4 CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bs4/bootstrap.min.css' %}" />
	<!-- Main Jquery -->
	<script type="text/javascript" src="{% static 'vendor/jquery.min.js' %}"></script>
	<!-- Bootstrap Js -->
	<script type="text/javascript" src="{% static '/vendor/bs4/bootstrap.min.js' %}"></script>
</head>
<body>
	<!-- Top News -->
	<nav class="navbar navbar-expand-lg navbar-dark bg-danger">
		<div class="container">
		  <a class="navbar-brand" href="/">NUBESS</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarNav">
		    <ul class="navbar-nav ml-auto">
		      <li class="nav-item active">
		        <a class="nav-link" href="/">Home</a>
		      </li>
		    <!--  <li class="nav-item">
		        <a class="nav-link" href="{% url 'all-news' %}">All News</a>
		      </li> -->
		      <li class="nav-item">
		        <a class="nav-link" href="{% url 'all-category' %}">All Categories</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="{% url 'contact' %}">Contact us</a>
		      </li>
		    </ul>
		  </div>
	  	</div>
    </nav>
     
    {% block content %}
    {% endblock %}

<hr/>
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
 
  </div>
</footer>
</body>
</html>

newsapp/templates/category-news.html
{% extends 'base.html' %}
{% block content %}
<main class="container mt-3 mb-5">
	<h3 class="border-bottom pb-1 my-4">{{category.title}}</h3>
    <!-- News Box -->
    {% for news in all_news %}
	<div class="card mb-4 shadow">
	  <div class="row no-gutters">
	    <div class="col-md-3">
            <img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
	    </div>
	    <div class="col-md-8">
	      <div class="card-body">
	        <h5 class="card-title">{{news.title}}</h5>
	        <p class="card-text">{{news.detail}}</p>
	        <p class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-primary">Read Full</a></p>
	      </div>
	    </div>
	  </div>
    </div>
    {% endfor %}
</main>
{% endblock %}

newsapp/templates/category.html
{% extends 'base.html' %}
{% block content %}
<main class="container mt-3 mb-5">
	<h3 class="border-bottom pb-1 my-4">All Categories</h3>
	<div class="row">
		<!-- Category Box -->
		{% for cat in cats %}
		<div class="col-md-4">
			<div class="card mb-3 shadow">
            <img src="/media/{{cat.category_image}}" class="card-img-top" alt="{{cat.title}}">
			  <div class="card-body">
			    <h5 class="card-title">{{cat.title}}</h5>
			    <hr/>
			    <p class="card-text"><a href="category/{{cat.id}}" class="btn btn-sm btn-primary">All News</a></p>
			  </div>
			</div>
		</div>
		{% endfor %}
	</div>
</main>
{% endblock %}

newsapp/templates/contact.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header bg-danger text-white"><i class="fa fa-envelope"></i> Contact us.
                </div>
                <div class="card-body">
                    <form>
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" class="form-control" id="name" aria-describedby="emailHelp" placeholder="Enter name" required>
                        </div>
                        <div class="form-group">
                            <label for="email">Email address</label>
                            <input type="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Enter email" required>
                            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                        </div>
                        <div class="form-group">
                            <label for="message">Message</label>
                            <textarea class="form-control" id="message" rows="6" required></textarea>
                        </div>
                        <div class="mx-auto">
                        <button type="submit" class="btn btn-danger text-right">Submit</button></div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-12 col-sm-4">
            <div class="card bg-light mb-3">
                <div class="card-header bg-danger text-white text-uppercase"><i class="fa fa-home"></i> Address</div>
                <div class="card-body">
                    <p>3 rue des Champs Elysées</p>
                    <p>75008 PARIS</p>
                    <p>France</p>
                    <p>Email : email@example.com</p>
                    <p>Tel. +33 12 56 11 51 84</p>

                </div>

            </div>
        </div>
    </div>
</div>
{% endblock content %}

newsapp/templates/detail.html
{% extends 'base.html' %}
{% block content %}
<main class="container mt-3 mb-5">
	<!-- featured news -->
	<div class="row my-3">
		<!-- Left -->
		<div class="col-md-8">
			<div class="card mb-3">
                <img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
			  <div class="card-body">
			    <h5 class="card-title">{{news.title}}</h5>
			    <hr/>
			    <p class="card-text">{{news.detail}}</p>
			  </div>
			  <div class="card-footer">
			  	In <a href="/category/{{news.category.id}}">{{news.category.title}}</a>
			  </div>
			</div>

			<!-- Comments -->
			<div class="card my-4">
				<h6 class="card-header">Add Comment</h6>
				<div class="card-body">
					{% for message in messages %}
					<p class="text-success">{{message}}</p>
					{% endfor %}
					<form method="post" action="/detail/{{news.id}}">
						{% csrf_token %}
						<div class="form-group row">
							<label class="col-md-2">Name<span class="text-danger">*</span></label>
							<div class="col-md-10">
								<input type="text" name="name" required class="form-control" />
							</div>
						</div>
						<div class="form-group row">
							<label class="col-md-2">Email<span class="text-danger">*</span></label>
							<div class="col-md-10">
								<input type="temailext" name="email" required class="form-control" />
							</div>
						</div>
						<div class="form-group row">
							<label class="col-md-2">Comment<span class="text-danger">*</span></label>
							<div class="col-md-10">
								<textarea class="form-control" name="message" required></textarea>
							</div>
						</div>
						<input type="submit" class="btn btn-primary" />
					</form>
				</div>
			</div>
			<!-- Previous Comments -->
			<div class="card my-4">
				<h6 class="card-header">Comments</h6>
				<div class="card-body">
					{% for comment in comments %}
					<blockquote class="blockquote text-right">
					  <p class="mb-0">{{comment.comment}}</p>
					  <footer class="blockquote-footer">{{comment.name}} <cite title="Source Title">{{comment.email}}</cite></footer>
					</blockquote>
					<hr/>
					{% endfor %}
				</div>
			</div>
		</div>
		<!-- Related News -->
		<div class="col-md-4">
			<h3 class="mb-3 border-bottom pb-1">From this Category</h3>
			<!-- Category Box -->
			{% for news in related_news %}
			<div class="card mb-3 shadow">
                <img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
			  <div class="card-body">
			    <h5 class="card-title">{{news.title}}</h5>
			    <hr/>
			    <p class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-primary">Read Full</a></p>
			  </div>
			</div>
			{% endfor %}
		</div>
	</div>
</main>
{% endblock %}

newsapp/templates/home.html
{% extends 'base.html' %}
{% block content %}
<main class="container mt-3 mb-5">
	<!-- featured news -->
	<div class="row my-3">
		<!-- Left -->
		<div class="col-md-7">
			<div class="card mb-3">
			  <img src="media/{{first_news.image}}" class="card-img-top" alt="{{first_news.title}}">
			  <div class="card-body">
			    <h5 class="card-title">{{first_news.title}}</h5>
			    <hr/>
			    <p class="card-text"><a href="/detail/{{first_news.id}}" class="btn btn-sm btn-primary">Read Full</a></p>
			  </div>
			</div>
		</div>
		<!-- Right -->
		<div class="col-md-5" style="max-height: 450px; overflow: auto;">
			{% for news in three_news %}
			<!-- News Box -->
			<div class="card">
			  <div class="row no-gutters">
			    <div class="col-md-4">
					<img src="media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
			    </div>
			    <div class="col-md-8">
			      <div class="card-body">
			        <h5 class="card-title">{{news.title}}</h5>
			        <p class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-primary">Read Full</a></p>
			      </div>
			    </div>
			  </div>
			</div>
			<hr/>
			{% endfor %}
		</div>
	</div>
	<!-- Category Wise News -->
	{% for category in three_categories %}
	<h3 class="border-bottom pb-1">{{category.title}} <a href="/category/{{category.id}}" class="float-right btn btn-sm btn-dark">In this Category</a></h3>
	<div class="row my-4">
		{% for news in category.news_set.all %}
			{% if forloop.counter < 5 %}
			<!-- News box -->
			<div class="col-md-3">
				<div class="card mb-3 shadow">
				<img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
				<div class="card-body">
					<h5 class="card-title">{{news.title}}</h5>
					<hr/>
					<p class="card-text"><a href="#" class="btn btn-sm btn-primary">Read Full</a></p>
				</div>
				</div>
			</div>
			{% endif %}
		{% endfor %}
	</div>
	{% endfor %}
	<!-- End Single Category -->
</main>
{% endblock %}